version: 2.1

orbs:
  node: circleci/node@4.7

workflows:
  sample:
    jobs:
      # The following line is removed to delete the job
      # - node/test:
      #   version: '16.10'
      #   pkg-manager: npm
